kind: Namespace
apiVersion: v1
metadata:
  name: kube-logging

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-data
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/usr/share/elasticsearch/data"
